### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [quozl/implode-activity#3]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by quozl** [comment]
No, I'm fine with where it is.  If you want a clone, fork it yourself. I'm not a member of Sugar Labs so can't do that myself.

**Comment by davelab6** [comment]
Please visit https://github.com/sugarlabs and accept your invitation, then you can make the transfer. 

I don't want to fork it from your repo, I want you to transfer it to the sugarlabs org, so that the github network graph looks right.

**Comment by quozl** [comment]
Please raise any network graph design issue with GitHub Inc.

**Comment by davelab6** [comment]
Why are you objecting to this?
